spring.application.name=projetSoutenance2026PME

# Connexion à PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/pme
spring.datasource.username=postgres
spring.datasource.password=postgres

server.port=8082

# Configuration Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Premier administrateur - développement
app.admin.username=admin
app.admin.email=admin@pme.local
app.admin.password=Admin12345

# JWT
app.jwt.secret=MaCleSecreteTresLonguePourJWTProjetPME2026Security
app.jwt.expiration=86400000

